// ============================================================
// NARI SAATHI — data.js
// All app content: UI translations + schemes + job resources
// ============================================================

const LANGUAGES = [
  { code: "en", label: "English", native: "English" },
  { code: "hi", label: "Hindi", native: "हिन्दी" },
  { code: "ta", label: "Tamil", native: "தமிழ்" },
  { code: "te", label: "Telugu", native: "తెలుగు" },
  { code: "bn", label: "Bengali", native: "বাংলা" },
  { code: "mr", label: "Marathi", native: "मराठी" },
];

// ----------------------------------------------------------
// UI STRINGS — every screen label, button, empty state, etc.
// Add a new language by adding one more key here (e.g. "kn": {...})
// ----------------------------------------------------------
const UI = {
  en: {
    appName: "Nari Saathi",
    tagline: "Every scheme. Every job. One place, in your language.",
    navHome: "Home",
    navSchemes: "Yojanas",
    navJobs: "Govt Jobs",
    navSaved: "Saved",
    searchPlaceholder: "Search schemes, jobs, categories...",
    heroTitle: "Your rights, your opportunities — explained simply",
    heroSub: "Government schemes and job openings for women across India. Verified sources. Direct links. No middlemen.",
    exploreSchemes: "Explore Yojanas",
    exploreJobs: "Explore Govt Jobs",
    categoriesTitle: "Browse by category",
    allCategories: "All",
    catEducation: "Education",
    catFinance: "Finance & Savings",
    catHealth: "Health & Maternity",
    catEntrepreneur: "Business & Loans",
    catSafety: "Safety & Legal Help",
    catEmployment: "Employment & Skill",
    catHousing: "Housing",
    eligibility: "Who can apply",
    benefits: "What you get",
    howToApply: "How to apply",
    officialLink: "Official website",
    ministry: "Managed by",
    save: "Save",
    saved: "Saved",
    unsave: "Remove",
    viewDetails: "View details",
    close: "Close",
    noResults: "No results found. Try a different word or category.",
    savedEmpty: "You haven't saved anything yet. Tap the bookmark icon on any scheme or job to keep it here.",
    schemesHeading: "Government Schemes for Women",
    schemesSub: "Tap any card to see full details, eligibility and the official link.",
    jobsHeading: "Government Job Resources for Women",
    jobsSub: "Official portals where verified job openings are posted. Listings change daily — always check the live site.",
    footerNote: "This app collects public information from official Government of India sources for easy access. Always confirm details on the official website before applying. It does not collect money or personal documents from you.",
    disclaimer: "Information last checked: August 2026. Scheme rules, amounts and links can change — always verify on the official site linked below before applying.",
    languageLabel: "Language",
    installApp: "Install this app",
    helplineTitle: "Need help right now?",
    helplineText: "Women Helpline (All India, 24x7): dial 181 or 1091",
    centralGovt: "Central Government",
    stateGovt: "State-level",
    private_: "Women-focused job platforms",
  },
  hi: {
    appName: "नारी साथी",
    tagline: "हर योजना। हर नौकरी। एक जगह, आपकी भाषा में।",
    navHome: "होम",
    navSchemes: "योजनाएं",
    navJobs: "सरकारी नौकरी",
    navSaved: "सहेजे गए",
    searchPlaceholder: "योजना, नौकरी, श्रेणी खोजें...",
    heroTitle: "आपके अधिकार, आपके अवसर — आसान भाषा में",
    heroSub: "पूरे भारत में महिलाओं के लिए सरकारी योजनाएं और नौकरियां। सत्यापित स्रोत। सीधे लिंक। कोई बिचौलिया नहीं।",
    exploreSchemes: "योजनाएं देखें",
    exploreJobs: "सरकारी नौकरियां देखें",
    categoriesTitle: "श्रेणी अनुसार देखें",
    allCategories: "सभी",
    catEducation: "शिक्षा",
    catFinance: "वित्त और बचत",
    catHealth: "स्वास्थ्य और मातृत्व",
    catEntrepreneur: "व्यापार और ऋण",
    catSafety: "सुरक्षा और कानूनी मदद",
    catEmployment: "रोज़गार और कौशल",
    catHousing: "आवास",
    eligibility: "कौन आवेदन कर सकता है",
    benefits: "आपको क्या मिलेगा",
    howToApply: "आवेदन कैसे करें",
    officialLink: "आधिकारिक वेबसाइट",
    ministry: "संचालित द्वारा",
    save: "सहेजें",
    saved: "सहेजा गया",
    unsave: "हटाएं",
    viewDetails: "पूरी जानकारी देखें",
    close: "बंद करें",
    noResults: "कोई परिणाम नहीं मिला। कोई और शब्द या श्रेणी आज़माएं।",
    savedEmpty: "आपने अभी तक कुछ सहेजा नहीं है। किसी भी योजना या नौकरी पर बुकमार्क आइकन दबाएं।",
    schemesHeading: "महिलाओं के लिए सरकारी योजनाएं",
    schemesSub: "पूरी जानकारी, पात्रता और आधिकारिक लिंक देखने के लिए किसी भी कार्ड पर टैप करें।",
    jobsHeading: "महिलाओं के लिए सरकारी नौकरी संसाधन",
    jobsSub: "आधिकारिक पोर्टल जहां सत्यापित नौकरियां पोस्ट होती हैं। सूची रोज़ बदलती है — हमेशा लाइव साइट देखें।",
    footerNote: "यह ऐप भारत सरकार के आधिकारिक स्रोतों से सार्वजनिक जानकारी इकट्ठा करता है। आवेदन करने से पहले हमेशा आधिकारिक वेबसाइट पर विवरण की पुष्टि करें। यह आपसे पैसे या व्यक्तिगत दस्तावेज़ नहीं लेता।",
    disclaimer: "जानकारी अंतिम बार जांची गई: अगस्त 2026। योजना के नियम, राशि और लिंक बदल सकते हैं — आवेदन से पहले हमेशा नीचे दी गई आधिकारिक वेबसाइट पर पुष्टि करें।",
    languageLabel: "भाषा",
    installApp: "यह ऐप इंस्टॉल करें",
    helplineTitle: "अभी मदद चाहिए?",
    helplineText: "महिला हेल्पलाइन (पूरे भारत में, 24x7): 181 या 1091 डायल करें",
    centralGovt: "केंद्र सरकार",
    stateGovt: "राज्य स्तर",
    private_: "महिला-केंद्रित नौकरी प्लेटफ़ॉर्म",
  },
  ta: {
    appName: "நாரி சாதி",
    tagline: "ஒவ்வொரு திட்டமும். ஒவ்வொரு வேலையும். ஒரே இடத்தில், உங்கள் மொழியில்.",
    navHome: "முகப்பு",
    navSchemes: "திட்டங்கள்",
    navJobs: "அரசு வேலைகள்",
    navSaved: "சேமிக்கப்பட்டவை",
    searchPlaceholder: "திட்டங்கள், வேலைகள், வகைகளைத் தேடுங்கள்...",
    heroTitle: "உங்கள் உரிமைகள், உங்கள் வாய்ப்புகள் — எளிமையாக",
    heroSub: "இந்தியா முழுவதும் பெண்களுக்கான அரசு திட்டங்களும் வேலை வாய்ப்புகளும். சரிபார்க்கப்பட்ட ஆதாரங்கள். நேரடி இணைப்புகள்.",
    exploreSchemes: "திட்டங்களைக் காண்க",
    exploreJobs: "அரசு வேலைகளைக் காண்க",
    categoriesTitle: "வகை வாரியாகப் பார்க்க",
    allCategories: "அனைத்தும்",
    catEducation: "கல்வி",
    catFinance: "நிதி மற்றும் சேமிப்பு",
    catHealth: "சுகாதாரம் மற்றும் மகப்பேறு",
    catEntrepreneur: "வணிகம் மற்றும் கடன்",
    catSafety: "பாதுகாப்பு மற்றும் சட்ட உதவி",
    catEmployment: "வேலைவாய்ப்பு மற்றும் திறன்",
    catHousing: "வீட்டுவசதி",
    eligibility: "யார் விண்ணப்பிக்கலாம்",
    benefits: "நீங்கள் பெறுவது",
    howToApply: "எப்படி விண்ணப்பிப்பது",
    officialLink: "அதிகாரப்பூர்வ இணையதளம்",
    ministry: "நிர்வகிப்பவர்",
    save: "சேமி",
    saved: "சேமிக்கப்பட்டது",
    unsave: "நீக்கு",
    viewDetails: "விவரங்களைக் காண்க",
    close: "மூடு",
    noResults: "முடிவுகள் இல்லை. வேறு வார்த்தை அல்லது வகையை முயற்சிக்கவும்.",
    savedEmpty: "நீங்கள் இதுவரை எதையும் சேமிக்கவில்லை. ஏதேனும் திட்டம் அல்லது வேலையில் உள்ள bookmark ஐகானை தட்டவும்.",
    schemesHeading: "பெண்களுக்கான அரசு திட்டங்கள்",
    schemesSub: "முழு விவரங்கள், தகுதி மற்றும் அதிகாரப்பூர்வ இணைப்பைக் காண எந்த அட்டையையும் தட்டவும்.",
    jobsHeading: "பெண்களுக்கான அரசு வேலை வளங்கள்",
    jobsSub: "சரிபார்க்கப்பட்ட வேலைகள் வெளியிடப்படும் அதிகாரப்பூர்வ போர்ட்டல்கள். பட்டியல் தினமும் மாறும் — எப்போதும் நேரடி தளத்தைப் பாருங்கள்.",
    footerNote: "இந்த ஆப் இந்திய அரசின் அதிகாரப்பூர்வ ஆதாரங்களிலிருந்து பொது தகவல்களை சேகரிக்கிறது. விண்ணப்பிக்கும் முன் எப்போதும் அதிகாரப்பூர்வ இணையதளத்தில் விவரங்களை உறுதிப்படுத்தவும்.",
    disclaimer: "தகவல் கடைசியாக சரிபார்க்கப்பட்டது: ஆகஸ்ட் 2026. திட்ட விதிகள், தொகைகள் மற்றும் இணைப்புகள் மாறலாம் — விண்ணப்பிக்கும் முன் அதிகாரப்பூர்வ தளத்தில் உறுதிப்படுத்தவும்.",
    languageLabel: "மொழி",
    installApp: "இந்த ஆப்பை நிறுவவும்",
    helplineTitle: "இப்போது உதவி வேண்டுமா?",
    helplineText: "பெண்கள் உதவி எண் (இந்தியா முழுவதும், 24x7): 181 அல்லது 1091",
    centralGovt: "மத்திய அரசு",
    stateGovt: "மாநில அளவில்",
    private_: "பெண்கள் சார்ந்த வேலை தளங்கள்",
  },
  te: {
    appName: "నారీ సాథి",
    tagline: "ప్రతి పథకం. ప్రతి ఉద్యోగం. ఒకే చోట, మీ భాషలో.",
    navHome: "హోమ్",
    navSchemes: "యోజనలు",
    navJobs: "ప్రభుత్వ ఉద్యోగాలు",
    navSaved: "సేవ్ చేసినవి",
    searchPlaceholder: "పథకాలు, ఉద్యోగాలు, వర్గాలు వెతకండి...",
    heroTitle: "మీ హక్కులు, మీ అవకాశాలు — సులభంగా",
    heroSub: "భారతదేశం అంతటా మహిళల కోసం ప్రభుత్వ పథకాలు మరియు ఉద్యోగ అవకాశాలు. ధృవీకరించిన మూలాలు. నేరుగా లింకులు.",
    exploreSchemes: "యోజనలు చూడండి",
    exploreJobs: "ప్రభుత్వ ఉద్యోగాలు చూడండి",
    categoriesTitle: "వర్గం వారీగా చూడండి",
    allCategories: "అన్నీ",
    catEducation: "విద్య",
    catFinance: "ఆర్థికం & పొదుపు",
    catHealth: "ఆరోగ్యం & ప్రసూతి",
    catEntrepreneur: "వ్యాపారం & రుణాలు",
    catSafety: "భద్రత & న్యాయ సహాయం",
    catEmployment: "ఉపాధి & నైపుణ్యం",
    catHousing: "గృహనిర్మాణం",
    eligibility: "ఎవరు దరఖాస్తు చేసుకోవచ్చు",
    benefits: "మీకు లభించేది",
    howToApply: "ఎలా దరఖాస్తు చేయాలి",
    officialLink: "అధికారిక వెబ్‌సైట్",
    ministry: "నిర్వహించేది",
    save: "సేవ్ చేయండి",
    saved: "సేవ్ చేయబడింది",
    unsave: "తీసివేయండి",
    viewDetails: "పూర్తి వివరాలు చూడండి",
    close: "మూసివేయండి",
    noResults: "ఫలితాలు లేవు. వేరే పదం లేదా వర్గం ప్రయత్నించండి.",
    savedEmpty: "మీరు ఇంకా ఏమీ సేవ్ చేయలేదు. ఏదైనా పథకం లేదా ఉద్యోగంపై బుక్‌మార్క్ ఐకాన్‌ను నొక్కండి.",
    schemesHeading: "మహిళల కోసం ప్రభుత్వ పథకాలు",
    schemesSub: "పూర్తి వివరాలు, అర్హత మరియు అధికారిక లింక్ చూడటానికి ఏదైనా కార్డుపై నొక్కండి.",
    jobsHeading: "మహిళల కోసం ప్రభుత్వ ఉద్యోగ వనరులు",
    jobsSub: "ధృవీకరించబడిన ఉద్యోగాలు పోస్ట్ చేయబడే అధికారిక పోర్టల్‌లు. జాబితా ప్రతిరోజూ మారుతుంది — ఎల్లప్పుడూ లైవ్ సైట్‌ను చూడండి.",
    footerNote: "ఈ యాప్ భారత ప్రభుత్వ అధికారిక వనరుల నుండి ప్రజా సమాచారాన్ని సేకరిస్తుంది. దరఖాస్తు చేసే ముందు ఎల్లప్పుడూ అధికారిక వెబ్‌సైట్‌లో వివరాలను నిర్ధారించుకోండి.",
    disclaimer: "సమాచారం చివరిసారి తనిఖీ చేయబడింది: ఆగస్టు 2026. పథక నియమాలు, మొత్తాలు మరియు లింకులు మారవచ్చు — దరఖాస్తుకు ముందు అధికారిక సైట్‌లో నిర్ధారించుకోండి.",
    languageLabel: "భాష",
    installApp: "ఈ యాప్‌ను ఇన్‌స్టాల్ చేయండి",
    helplineTitle: "ఇప్పుడు సహాయం కావాలా?",
    helplineText: "మహిళా హెల్ప్‌లైన్ (భారతదేశం మొత్తం, 24x7): 181 లేదా 1091 డయల్ చేయండి",
    centralGovt: "కేంద్ర ప్రభుత్వం",
    stateGovt: "రాష్ట్ర స్థాయి",
    private_: "మహిళా-కేంద్రీకృత ఉద్యోగ వేదికలు",
  },
  bn: {
    appName: "নারী সাথী",
    tagline: "প্রতিটি প্রকল্প। প্রতিটি চাকরি। এক জায়গায়, আপনার ভাষায়।",
    navHome: "হোম",
    navSchemes: "যোজনা",
    navJobs: "সরকারি চাকরি",
    navSaved: "সংরক্ষিত",
    searchPlaceholder: "প্রকল্প, চাকরি, বিভাগ খুঁজুন...",
    heroTitle: "আপনার অধিকার, আপনার সুযোগ — সহজভাবে",
    heroSub: "সারা ভারতে মহিলাদের জন্য সরকারি প্রকল্প এবং চাকরির সুযোগ। যাচাইকৃত উৎস। সরাসরি লিঙ্ক।",
    exploreSchemes: "যোজনা দেখুন",
    exploreJobs: "সরকারি চাকরি দেখুন",
    categoriesTitle: "বিভাগ অনুযায়ী দেখুন",
    allCategories: "সব",
    catEducation: "শিক্ষা",
    catFinance: "অর্থ ও সঞ্চয়",
    catHealth: "স্বাস্থ্য ও মাতৃত্ব",
    catEntrepreneur: "ব্যবসা ও ঋণ",
    catSafety: "নিরাপত্তা ও আইনি সহায়তা",
    catEmployment: "কর্মসংস্থান ও দক্ষতা",
    catHousing: "আবাসন",
    eligibility: "কে আবেদন করতে পারবেন",
    benefits: "আপনি কী পাবেন",
    howToApply: "কীভাবে আবেদন করবেন",
    officialLink: "সরকারি ওয়েবসাইট",
    ministry: "পরিচালনায়",
    save: "সংরক্ষণ করুন",
    saved: "সংরক্ষিত হয়েছে",
    unsave: "সরান",
    viewDetails: "বিস্তারিত দেখুন",
    close: "বন্ধ করুন",
    noResults: "কোনো ফলাফল পাওয়া যায়নি। অন্য শব্দ বা বিভাগ চেষ্টা করুন।",
    savedEmpty: "আপনি এখনও কিছু সংরক্ষণ করেননি। যেকোনো প্রকল্প বা চাকরিতে বুকমার্ক আইকনে চাপুন।",
    schemesHeading: "মহিলাদের জন্য সরকারি প্রকল্প",
    schemesSub: "সম্পূর্ণ বিবরণ, যোগ্যতা এবং সরকারি লিঙ্ক দেখতে যেকোনো কার্ডে চাপুন।",
    jobsHeading: "মহিলাদের জন্য সরকারি চাকরির সংস্থান",
    jobsSub: "যাচাইকৃত চাকরির খবর পোস্ট করা হয় এমন সরকারি পোর্টাল। তালিকা প্রতিদিন পরিবর্তন হয় — সবসময় লাইভ সাইট দেখুন।",
    footerNote: "এই অ্যাপটি ভারত সরকারের সরকারি উৎস থেকে জনসাধারণের তথ্য সংগ্রহ করে। আবেদন করার আগে সর্বদা সরকারি ওয়েবসাইটে বিবরণ নিশ্চিত করুন।",
    disclaimer: "তথ্য সর্বশেষ পরীক্ষা করা হয়েছে: আগস্ট ২০২৬। প্রকল্পের নিয়ম, পরিমাণ এবং লিঙ্ক পরিবর্তন হতে পারে — আবেদনের আগে সরকারি সাইটে নিশ্চিত করুন।",
    languageLabel: "ভাষা",
    installApp: "এই অ্যাপ ইনস্টল করুন",
    helplineTitle: "এখনই সাহায্য দরকার?",
    helplineText: "মহিলা হেল্পলাইন (সারা ভারতে, 24x7): 181 বা 1091 ডায়াল করুন",
    centralGovt: "কেন্দ্রীয় সরকার",
    stateGovt: "রাজ্য স্তর",
    private_: "মহিলা-কেন্দ্রিক চাকরির প্ল্যাটফর্ম",
  },
  mr: {
    appName: "नारी साथी",
    tagline: "प्रत्येक योजना. प्रत्येक नोकरी. एकाच ठिकाणी, तुमच्या भाषेत.",
    navHome: "मुख्यपृष्ठ",
    navSchemes: "योजना",
    navJobs: "सरकारी नोकरी",
    navSaved: "जतन केलेले",
    searchPlaceholder: "योजना, नोकरी, श्रेणी शोधा...",
    heroTitle: "तुमचे हक्क, तुमच्या संधी — सोप्या भाषेत",
    heroSub: "संपूर्ण भारतातील महिलांसाठी सरकारी योजना आणि नोकऱ्या. सत्यापित स्रोत. थेट लिंक.",
    exploreSchemes: "योजना पहा",
    exploreJobs: "सरकारी नोकऱ्या पहा",
    categoriesTitle: "श्रेणीनुसार पहा",
    allCategories: "सर्व",
    catEducation: "शिक्षण",
    catFinance: "वित्त आणि बचत",
    catHealth: "आरोग्य आणि मातृत्व",
    catEntrepreneur: "व्यवसाय आणि कर्ज",
    catSafety: "सुरक्षा आणि कायदेशीर मदत",
    catEmployment: "रोजगार आणि कौशल्य",
    catHousing: "घरबांधणी",
    eligibility: "कोण अर्ज करू शकते",
    benefits: "तुम्हाला काय मिळेल",
    howToApply: "अर्ज कसा करावा",
    officialLink: "अधिकृत वेबसाइट",
    ministry: "व्यवस्थापन",
    save: "जतन करा",
    saved: "जतन केले",
    unsave: "काढा",
    viewDetails: "सविस्तर पहा",
    close: "बंद करा",
    noResults: "कोणतेही निकाल आढळले नाहीत. वेगळा शब्द किंवा श्रेणी वापरून पहा.",
    savedEmpty: "तुम्ही अद्याप काहीही जतन केलेले नाही. कोणत्याही योजनेवर किंवा नोकरीवर बुकमार्क आयकॉन दाबा.",
    schemesHeading: "महिलांसाठी सरकारी योजना",
    schemesSub: "संपूर्ण तपशील, पात्रता आणि अधिकृत लिंक पाहण्यासाठी कोणत्याही कार्डवर टॅप करा.",
    jobsHeading: "महिलांसाठी सरकारी नोकरी संसाधने",
    jobsSub: "सत्यापित नोकऱ्या पोस्ट केल्या जाणारे अधिकृत पोर्टल. यादी दररोज बदलते — नेहमी लाइव्ह साइट पहा.",
    footerNote: "हे अ‍ॅप भारत सरकारच्या अधिकृत स्रोतांकडून सार्वजनिक माहिती गोळा करते. अर्ज करण्यापूर्वी नेहमी अधिकृत वेबसाइटवर तपशील तपासा.",
    disclaimer: "माहिती शेवटची तपासली: ऑगस्ट 2026. योजनेचे नियम, रक्कम आणि लिंक बदलू शकतात — अर्ज करण्यापूर्वी अधिकृत साइटवर खात्री करा.",
    languageLabel: "भाषा",
    installApp: "हे अ‍ॅप इन्स्टॉल करा",
    helplineTitle: "आत्ता मदत हवी आहे?",
    helplineText: "महिला हेल्पलाइन (संपूर्ण भारत, 24x7): 181 किंवा 1091 डायल करा",
    centralGovt: "केंद्र सरकार",
    stateGovt: "राज्य स्तर",
    private_: "महिला-केंद्रित नोकरी व्यासपीठ",
  },
};

// ----------------------------------------------------------
// SCHEMES — real, verifiable Government of India schemes.
// Full text supplied in English + Hindi to start.
// To add another language: add a "ta"/"te"/"bn"/"mr" key
// inside name/description/eligibility/benefits/howToApply
// for that scheme — the app will fall back to English
// automatically for any language not yet filled in.
// ----------------------------------------------------------
const SCHEMES = [
  {
    id: "bbbp",
    category: "education",
    ministry: "Ministry of Women & Child Development",
    officialLink: "https://wcd.gov.in/bbbp-scheme",
    name: { en: "Beti Bachao Beti Padhao (BBBP)", hi: "बेटी बचाओ बेटी पढ़ाओ" },
    description: {
      en: "A national campaign to stop the decline in the child sex ratio, protect and educate the girl child, and change mindsets around daughters.",
      hi: "बाल लिंगानुपात में गिरावट रोकने, बालिका की सुरक्षा और शिक्षा सुनिश्चित करने तथा बेटियों के प्रति सोच बदलने का राष्ट्रीय अभियान।",
    },
    eligibility: {
      en: "All families with a girl child; the scheme runs as a district-level campaign, so benefits and awareness activities vary by district.",
      hi: "बालिका वाले सभी परिवार पात्र हैं; यह जिला स्तर पर चलने वाला अभियान है, इसलिए लाभ और गतिविधियां जिले अनुसार अलग हो सकती हैं।",
    },
    benefits: {
      en: "Awareness drives, school enrolment support for girls, convergence with Sukanya Samriddhi Yojana for savings.",
      hi: "जागरूकता अभियान, बालिकाओं के स्कूल नामांकन में सहायता, सुकन्या समृद्धि योजना के साथ बचत हेतु समन्वय।",
    },
    howToApply: {
      en: "No individual application — contact your local Anganwadi Centre or District Women & Child Development Office to access linked benefits.",
      hi: "कोई व्यक्तिगत आवेदन नहीं — जुड़े हुए लाभ पाने के लिए अपने नज़दीकी आंगनवाड़ी केंद्र या जिला महिला एवं बाल विकास कार्यालय से संपर्क करें।",
    },
  },
  {
    id: "ssy",
    category: "finance",
    ministry: "Ministry of Finance / India Post",
    officialLink: "https://www.nsiindia.gov.in/",
    name: { en: "Sukanya Samriddhi Yojana (SSY)", hi: "सुकन्या समृद्धि योजना" },
    description: {
      en: "A long-term savings account for a girl child, offering one of the highest government-backed interest rates, meant to build a fund for her education and marriage.",
      hi: "बालिका के लिए दीर्घकालिक बचत खाता, जो सरकार-समर्थित सबसे अच्छी ब्याज दरों में से एक देता है, ताकि उसकी शिक्षा और विवाह के लिए धन जमा हो सके।",
    },
    eligibility: {
      en: "Parents or legal guardians can open the account for a girl child from birth until she turns 10 years old. Only one account per girl child (max two per family, three in case of twins).",
      hi: "माता-पिता या कानूनी अभिभावक बालिका के जन्म से 10 वर्ष की आयु तक खाता खोल सकते हैं। एक बालिका के लिए केवल एक खाता (परिवार में अधिकतम दो, जुड़वां होने पर तीन)।",
    },
    benefits: {
      en: "Government-fixed interest rate (revised quarterly), full tax exemption on deposit, interest and maturity amount. Minimum deposit ₹250/year, maximum ₹1.5 lakh/year.",
      hi: "सरकार द्वारा तय ब्याज दर (हर तिमाही संशोधित), जमा, ब्याज और परिपक्वता राशि पर पूर्ण कर छूट। न्यूनतम जमा ₹250/वर्ष, अधिकतम ₹1.5 लाख/वर्ष।",
    },
    howToApply: {
      en: "Visit any post office or authorised bank branch with the girl's birth certificate and the guardian's ID/address proof to open the account.",
      hi: "बालिका का जन्म प्रमाण पत्र और अभिभावक का पहचान/पता प्रमाण लेकर किसी भी डाकघर या अधिकृत बैंक शाखा में जाएं और खाता खोलें।",
    },
  },
  {
    id: "pmmvy",
    category: "health",
    ministry: "Ministry of Women & Child Development",
    officialLink: "https://pmmvy.wcd.gov.in/",
    name: { en: "Pradhan Mantri Matru Vandana Yojana (PMMVY)", hi: "प्रधानमंत्री मातृ वंदना योजना" },
    description: {
      en: "A maternity benefit scheme providing cash incentives to pregnant and lactating mothers for their first living child, to support health and nutrition during pregnancy.",
      hi: "गर्भवती और स्तनपान कराने वाली माताओं को पहले जीवित बच्चे के लिए नकद प्रोत्साहन देने वाली मातृत्व लाभ योजना, ताकि गर्भावस्था के दौरान स्वास्थ्य और पोषण को सहयोग मिले।",
    },
    eligibility: {
      en: "Pregnant women and lactating mothers (for their first living child), aged 19 years or above, excluding those already receiving similar benefits as government employees.",
      hi: "19 वर्ष या उससे अधिक आयु की गर्भवती महिलाएं और स्तनपान कराने वाली माताएं (पहले जीवित बच्चे के लिए), सरकारी कर्मचारी के रूप में समान लाभ पहले से पाने वालों को छोड़कर।",
    },
    benefits: {
      en: "₹5,000 in three instalments during pregnancy/after birth, plus an additional ₹1,000 under Janani Suraksha Yojana on institutional delivery — totalling around ₹6,000.",
      hi: "गर्भावस्था/जन्म के बाद तीन किश्तों में ₹5,000, तथा संस्थागत प्रसव पर जननी सुरक्षा योजना के तहत अतिरिक्त ₹1,000 — कुल लगभग ₹6,000।",
    },
    howToApply: {
      en: "Register at your nearest Anganwadi Centre or approved health facility, or apply online through the PMMVY portal / PMMVY mobile app.",
      hi: "अपने नज़दीकी आंगनवाड़ी केंद्र या मान्यता प्राप्त स्वास्थ्य केंद्र पर पंजीकरण करें, या PMMVY पोर्टल/PMMVY मोबाइल ऐप से ऑनलाइन आवेदन करें।",
    },
  },
  {
    id: "standup",
    category: "entrepreneur",
    ministry: "Department of Financial Services, Ministry of Finance",
    officialLink: "https://www.standupmitra.in/",
    name: { en: "Stand-Up India Scheme", hi: "स्टैंड-अप इंडिया योजना" },
    description: {
      en: "Facilitates bank loans for setting up greenfield enterprises in manufacturing, services, trading or agri-allied sectors, with a dedicated focus on women entrepreneurs.",
      hi: "विनिर्माण, सेवा, व्यापार या कृषि-संबद्ध क्षेत्रों में नए (ग्रीनफील्ड) उद्यम स्थापित करने के लिए बैंक ऋण की सुविधा, महिला उद्यमियों पर विशेष ध्यान के साथ।",
    },
    eligibility: {
      en: "Women above 18 years setting up a new enterprise; at least one woman borrower per bank branch is expected to be covered.",
      hi: "18 वर्ष से अधिक आयु की महिलाएं जो नया उद्यम शुरू कर रही हैं; प्रत्येक बैंक शाखा से कम से कम एक महिला उधारकर्ता को शामिल करने का लक्ष्य।",
    },
    benefits: {
      en: "Bank loans between ₹10 lakh and ₹1 crore, composite loan covering both term loan and working capital, handholding support for the application.",
      hi: "₹10 लाख से ₹1 करोड़ तक का बैंक ऋण, टर्म लोन और वर्किंग कैपिटल दोनों को कवर करने वाला समग्र ऋण, आवेदन में सहायता।",
    },
    howToApply: {
      en: "Apply online on the Stand-Up India portal, or approach the nearest bank branch or Stand-Up India / Stand-Up Connect Centre (SUCC) directly.",
      hi: "स्टैंड-अप इंडिया पोर्टल पर ऑनलाइन आवेदन करें, या सीधे नज़दीकी बैंक शाखा या स्टैंड-अप कनेक्ट सेंटर (SUCC) से संपर्क करें।",
    },
  },
  {
    id: "mudra",
    category: "entrepreneur",
    ministry: "Ministry of Finance",
    officialLink: "https://www.mudra.org.in/",
    name: { en: "Pradhan Mantri Mudra Yojana (PMMY)", hi: "प्रधानमंत्री मुद्रा योजना" },
    description: {
      en: "Provides collateral-free loans up to ₹20 lakh to non-corporate, non-farm small and micro enterprises — widely used by women running small businesses like tailoring, beauty parlours, and retail.",
      hi: "गैर-कॉर्पोरेट, गैर-कृषि छोटे और सूक्ष्म उद्यमों को ₹20 लाख तक का बिना जमानत ऋण देती है — सिलाई, ब्यूटी पार्लर, खुदरा जैसे छोटे व्यवसाय चलाने वाली महिलाओं द्वारा व्यापक रूप से उपयोग की जाती है।",
    },
    eligibility: {
      en: "Any Indian citizen with a business plan for a non-farm income-generating activity in manufacturing, trading or services.",
      hi: "विनिर्माण, व्यापार या सेवा क्षेत्र में गैर-कृषि आय-सृजन गतिविधि की व्यवसाय योजना रखने वाला कोई भी भारतीय नागरिक।",
    },
    benefits: {
      en: "Loans under three categories — Shishu (up to ₹50,000), Kishor (₹50,000 to ₹5 lakh), and Tarun/Tarun Plus (₹5 lakh to ₹20 lakh) — with no collateral required.",
      hi: "तीन श्रेणियों में ऋण — शिशु (₹50,000 तक), किशोर (₹50,000 से ₹5 लाख), और तरुण/तरुण प्लस (₹5 लाख से ₹20 लाख) — बिना किसी जमानत के।",
    },
    howToApply: {
      en: "Apply through any bank, NBFC, or Micro Finance Institution, or online via the udyamimitra.in portal.",
      hi: "किसी भी बैंक, NBFC या माइक्रो फाइनेंस संस्था के माध्यम से, या udyamimitra.in पोर्टल पर ऑनलाइन आवेदन करें।",
    },
  },
  {
    id: "lakhpati-didi",
    category: "employment",
    ministry: "Ministry of Rural Development (DAY-NRLM)",
    officialLink: "https://nrlm.gov.in/",
    name: { en: "Lakhpati Didi Initiative", hi: "लखपति दीदी योजना" },
    description: {
      en: "A mission to help women in rural Self-Help Groups (SHGs) earn a sustainable annual household income of over ₹1 lakh, through skills, credit access and market linkage.",
      hi: "ग्रामीण स्वयं सहायता समूहों (SHG) की महिलाओं को कौशल, ऋण सुविधा और बाजार संपर्क के माध्यम से ₹1 लाख से अधिक की स्थायी वार्षिक घरेलू आय अर्जित करने में मदद करने का मिशन।",
    },
    eligibility: {
      en: "Women who are members of a Self-Help Group under DAY-NRLM (National Rural Livelihood Mission).",
      hi: "DAY-NRLM (राष्ट्रीय ग्रामीण आजीविका मिशन) के तहत स्वयं सहायता समूह की सदस्य महिलाएं।",
    },
    benefits: {
      en: "Skill training (e.g. plumbing, LED bulb making, drone operation), access to bank credit, and support to market SHG products.",
      hi: "कौशल प्रशिक्षण (जैसे प्लंबिंग, LED बल्ब निर्माण, ड्रोन संचालन), बैंक ऋण तक पहुंच, और SHG उत्पादों के विपणन में सहायता।",
    },
    howToApply: {
      en: "Join a Self-Help Group through your local NRLM/State Rural Livelihood Mission office or Gram Panchayat — no separate individual application is needed once in an SHG.",
      hi: "अपने स्थानीय NRLM/राज्य ग्रामीण आजीविका मिशन कार्यालय या ग्राम पंचायत के माध्यम से स्वयं सहायता समूह से जुड़ें — SHG में शामिल होने पर अलग से आवेदन की आवश्यकता नहीं।",
    },
  },
  {
    id: "ujjwala",
    category: "housing",
    ministry: "Ministry of Petroleum & Natural Gas",
    officialLink: "https://www.pmuy.gov.in/",
    name: { en: "Pradhan Mantri Ujjwala Yojana (PMUY)", hi: "प्रधानमंत्री उज्ज्वला योजना" },
    description: {
      en: "Provides free LPG gas connections to women from low-income households, replacing unsafe cooking fuels like firewood and coal with clean cooking gas.",
      hi: "निम्न-आय वाले परिवारों की महिलाओं को मुफ्त एलपीजी गैस कनेक्शन प्रदान करती है, लकड़ी और कोयले जैसे असुरक्षित ईंधन को स्वच्छ रसोई गैस से बदलती है।",
    },
    eligibility: {
      en: "Adult women from Below Poverty Line (BPL) or other eligible low-income households, as per the list of eligible categories on the official portal, who do not already have an LPG connection.",
      hi: "गरीबी रेखा से नीचे (BPL) या अन्य पात्र निम्न-आय वाले परिवारों की वयस्क महिलाएं, जिनके पास पहले से एलपीजी कनेक्शन नहीं है (आधिकारिक पोर्टल पर पात्र श्रेणियों की सूची अनुसार)।",
    },
    benefits: {
      en: "Free LPG connection with financial support for the first refill and stove, in the name of the woman of the household.",
      hi: "घर की महिला के नाम पर मुफ्त एलपीजी कनेक्शन, पहली रिफिल और चूल्हे के लिए वित्तीय सहायता के साथ।",
    },
    howToApply: {
      en: "Apply online on the PMUY portal or visit your nearest LPG distributor with identity proof, address proof and BPL/income certificate.",
      hi: "PMUY पोर्टल पर ऑनलाइन आवेदन करें या पहचान प्रमाण, पता प्रमाण और BPL/आय प्रमाण पत्र लेकर नज़दीकी एलपीजी वितरक के पास जाएं।",
    },
  },
  {
    id: "onestop",
    category: "safety",
    ministry: "Ministry of Women & Child Development",
    officialLink: "https://wcd.gov.in/",
    name: { en: "One Stop Centre Scheme (Sakhi)", hi: "वन स्टॉप सेंटर योजना (सखी)" },
    description: {
      en: "Provides integrated support to women affected by violence — medical aid, police assistance, legal aid, psychological counselling and temporary shelter — under one roof, in every district.",
      hi: "हिंसा से प्रभावित महिलाओं को एक ही छत के नीचे चिकित्सा सहायता, पुलिस सहायता, कानूनी सहायता, मनोवैज्ञानिक परामर्श और अस्थायी आश्रय जैसी एकीकृत सहायता प्रत्येक जिले में प्रदान करती है।",
    },
    eligibility: {
      en: "Any woman affected by violence, irrespective of age, class, caste, religion, education or marital status.",
      hi: "आयु, वर्ग, जाति, धर्म, शिक्षा या वैवाहिक स्थिति की परवाह किए बिना, हिंसा से प्रभावित कोई भी महिला।",
    },
    benefits: {
      en: "Free medical, legal, police and psychosocial support, plus temporary shelter (up to 5 days, extendable), all coordinated from a single centre.",
      hi: "मुफ्त चिकित्सा, कानूनी, पुलिस और मनोसामाजिक सहायता, साथ ही अस्थायी आश्रय (5 दिनों तक, बढ़ाया जा सकता है), सब एक ही केंद्र से समन्वित।",
    },
    howToApply: {
      en: "Walk in directly to the nearest One Stop Centre (Sakhi Kendra), or call the Women Helpline 181 for guidance and referral.",
      hi: "सीधे नज़दीकी वन स्टॉप सेंटर (सखी केंद्र) जाएं, या मार्गदर्शन और संदर्भ हेतु महिला हेल्पलाइन 181 पर कॉल करें।",
    },
  },
  {
    id: "workinghostel",
    category: "housing",
    ministry: "Ministry of Women & Child Development",
    officialLink: "https://wcd.gov.in/",
    name: { en: "Working Women Hostel Scheme", hi: "कामकाजी महिला छात्रावास योजना" },
    description: {
      en: "Supports the construction/running of hostels for working women in cities and towns, including a daycare facility for their children, to enable safe access to employment.",
      hi: "शहरों और कस्बों में कामकाजी महिलाओं के लिए छात्रावासों के निर्माण/संचालन में सहायता, उनके बच्चों के लिए डे-केयर सुविधा सहित, ताकि रोजगार तक सुरक्षित पहुंच सुनिश्चित हो सके।",
    },
    eligibility: {
      en: "Working women (single, widowed, divorced, separated or married but whose husband/family lives elsewhere), generally with individual income limits set by the implementing organisation.",
      hi: "कामकाजी महिलाएं (अविवाहित, विधवा, तलाकशुदा, अलग रह रही या विवाहित लेकिन जिनका पति/परिवार अन्यत्र रहता है), आमतौर पर कार्यान्वयन संस्था द्वारा तय आय सीमा के अनुसार।",
    },
    benefits: {
      en: "Safe, affordable hostel accommodation close to place of work, plus daycare for children aged 0–12 years where available.",
      hi: "कार्यस्थल के नज़दीक सुरक्षित, किफायती छात्रावास आवास, तथा उपलब्ध होने पर 0-12 वर्ष के बच्चों के लिए डे-केयर।",
    },
    howToApply: {
      en: "Apply directly to a hostel run by an NGO/organisation implementing this scheme in your city; contact your District Women & Child Development Office for a list of hostels.",
      hi: "अपने शहर में इस योजना को लागू करने वाली NGO/संस्था द्वारा संचालित छात्रावास में सीधे आवेदन करें; छात्रावासों की सूची के लिए अपने जिला महिला एवं बाल विकास कार्यालय से संपर्क करें।",
    },
  },
  {
    id: "shebox",
    category: "safety",
    ministry: "Ministry of Women & Child Development",
    officialLink: "https://shebox.wcd.gov.in/",
    name: { en: "SHe-Box (Sexual Harassment Electronic Box)", hi: "शी-बॉक्स" },
    description: {
      en: "An online portal for women, in the workplace or otherwise, to file complaints related to sexual harassment for prompt redressal.",
      hi: "कार्यस्थल पर या अन्यत्र महिलाओं के लिए यौन उत्पीड़न से संबंधित शिकायतें दर्ज करने और शीघ्र समाधान पाने हेतु ऑनलाइन पोर्टल।",
    },
    eligibility: {
      en: "Any working woman, in the government or private sector, facing sexual harassment at the workplace.",
      hi: "सरकारी या निजी क्षेत्र में कार्यस्थल पर यौन उत्पीड़न का सामना कर रही कोई भी कामकाजी महिला।",
    },
    benefits: {
      en: "Direct online complaint filing that is routed to the concerned Internal Committee (IC) or Local Committee (LC) for time-bound action.",
      hi: "सीधी ऑनलाइन शिकायत दर्ज करने की सुविधा, जो समयबद्ध कार्रवाई हेतु संबंधित आंतरिक समिति (IC) या स्थानीय समिति (LC) को भेजी जाती है।",
    },
    howToApply: {
      en: "File a complaint directly on the SHe-Box portal with details of the incident and workplace.",
      hi: "घटना और कार्यस्थल के विवरण के साथ SHe-Box पोर्टल पर सीधे शिकायत दर्ज करें।",
    },
  },
];

// ----------------------------------------------------------
// JOB RESOURCES — verified, official / well-known portals.
// Live listings change daily, so we link to the source of
// truth instead of hard-coding job posts that go stale.
// ----------------------------------------------------------
const JOB_RESOURCES = [
  {
    id: "ncs",
    group: "central",
    name: { en: "National Career Service (NCS)", hi: "राष्ट्रीय करियर सेवा" },
    description: {
      en: "The Government of India's official job portal (Ministry of Labour & Employment) with a dedicated filter for women job-seekers, careers counselling and skill training links.",
      hi: "भारत सरकार का आधिकारिक जॉब पोर्टल (श्रम एवं रोज़गार मंत्रालय), जिसमें महिला नौकरी खोजने वालों के लिए विशेष फ़िल्टर, करियर परामर्श और कौशल प्रशिक्षण लिंक मौजूद हैं।",
    },
    link: "https://www.ncs.gov.in/",
  },
  {
    id: "employmentnews",
    group: "central",
    name: { en: "Employment News (Rozgar Samachar)", hi: "रोज़गार समाचार" },
    description: {
      en: "The Government of India's official weekly employment newspaper listing central government vacancies, results and admit cards.",
      hi: "भारत सरकार का आधिकारिक साप्ताहिक रोज़गार समाचार पत्र, जिसमें केंद्र सरकार की रिक्तियां, परिणाम और प्रवेश पत्र सूचीबद्ध होते हैं।",
    },
    link: "https://www.employmentnews.gov.in/",
  },
  {
    id: "ssc",
    group: "central",
    name: { en: "Staff Selection Commission (SSC)", hi: "कर्मचारी चयन आयोग" },
    description: {
      en: "Recruits staff for various posts in ministries, departments and subordinate offices of the Government of India.",
      hi: "भारत सरकार के मंत्रालयों, विभागों और अधीनस्थ कार्यालयों में विभिन्न पदों के लिए कर्मचारियों की भर्ती करता है।",
    },
    link: "https://ssc.gov.in/",
  },
  {
    id: "upsc",
    group: "central",
    name: { en: "Union Public Service Commission (UPSC)", hi: "संघ लोक सेवा आयोग" },
    description: {
      en: "Conducts examinations for recruitment to All India Services and Central Civil Services, including IAS, IPS and IFS.",
      hi: "IAS, IPS और IFS सहित अखिल भारतीय सेवाओं और केंद्रीय सिविल सेवाओं में भर्ती के लिए परीक्षाएं आयोजित करता है।",
    },
    link: "https://upsc.gov.in/",
  },
  {
    id: "ibps",
    group: "central",
    name: { en: "IBPS (Banking Sector Recruitment)", hi: "आईबीपीएस (बैंकिंग भर्ती)" },
    description: {
      en: "Institute of Banking Personnel Selection — conducts common recruitment for clerks, probationary officers and specialist officers across public sector banks.",
      hi: "बैंकिंग कार्मिक चयन संस्थान — सार्वजनिक क्षेत्र के बैंकों में क्लर्क, प्रोबेशनरी अधिकारी और विशेषज्ञ अधिकारियों के लिए सामान्य भर्ती आयोजित करता है।",
    },
    link: "https://www.ibps.in/",
  },
  {
    id: "ncw",
    group: "central",
    name: { en: "National Commission for Women (NCW)", hi: "राष्ट्रीय महिला आयोग" },
    description: {
      en: "Statutory body for women's rights in India — also a good source for internships, awareness material, and complaint redressal related to workplace issues.",
      hi: "भारत में महिला अधिकारों हेतु सांविधिक निकाय — इंटर्नशिप, जागरूकता सामग्री, और कार्यस्थल संबंधी शिकायत निवारण के लिए भी एक अच्छा स्रोत।",
    },
    link: "https://ncw.nic.in/",
  },
  {
    id: "jobsforher",
    group: "private",
    name: { en: "JobsForHer", hi: "जॉब्सफॉरहर" },
    description: {
      en: "A well-known women-focused career platform in India connecting women (including those restarting after a career break) with employers across sectors.",
      hi: "भारत का जाना-माना महिला-केंद्रित करियर प्लेटफ़ॉर्म, जो महिलाओं (करियर ब्रेक के बाद दोबारा शुरुआत करने वालों सहित) को विभिन्न क्षेत्रों के नियोक्ताओं से जोड़ता है।",
    },
    link: "https://www.jobsforher.com/",
  },
  {
    id: "state-portals",
    group: "state",
    name: { en: "State Employment Portals", hi: "राज्य रोज़गार पोर्टल" },
    description: {
      en: "Most states run their own job/recruitment portal (e.g. state PSC boards, state skill missions). Search '[Your State] employment exchange' or '[Your State] PSC' to find yours.",
      hi: "अधिकतर राज्यों का अपना नौकरी/भर्ती पोर्टल है (जैसे राज्य लोक सेवा आयोग, राज्य कौशल मिशन)। अपना पोर्टल खोजने हेतु '[आपका राज्य] रोज़गार कार्यालय' या '[आपका राज्य] PSC' खोजें।",
    },
    link: "https://www.ncs.gov.in/",
  },
];

const CATEGORY_ICONS = {
  education: "🎓",
  finance: "💰",
  health: "🩺",
  entrepreneur: "🧵",
  safety: "🛡️",
  employment: "🌾",
  housing: "🏠",
};
